/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type PaginatedDto = {
  total: number;
  limit: number;
  offset: number;
  count: number;
  results: any[];
};

export type NftTypeDto = {
  id: string;
  name: string;
  description?: string | null;
};

export type FileDto = {
  id: string;
  name: string;
  tags: string[];
  mime_type: string;
  url: string;
  key: string;
  campaign_id: string;
  created_by_id: string;
  /**
   * @format date-time
   */
  created_at?: string;
  /**
   * @format date-time
   */
  updated_at?: string;
};

export type UserNftDto = {
  nft_id: string;
  user_id: string;
  campaign_id?: string | null;
  nft_type: NftTypeDto;
  name: string;
  description?: string | null;
  attributes?: Record<string, any> | null;
  supply?: number | null;
  file: FileDto;
};

export type ChainDto = {
  id: string;
  name: string;
  description?: string | null;
};

export type RegisterUserDto = {
  email?: string;
  wallet_address: string;
  chain_id: string;
  wallet_type: "Ramper" | "SelfCreated";
};

export type ProfileDto = {
  id: string;
  wallet_address: string;
  chain_id: string;
  user_id: string;
  created_by_id: string;
  /**
   * @format date-time
   */
  created_at?: string;
  /**
   * @format date-time
   */
  updated_at?: string;
};

export type UserDto = {
  id: string;
  email: string;
  username: string;
  role: "Admin" | "User";
  provider?: "Apple" | "Facebook" | "Google";
  provider_id?: string;
  profile?: ProfileDto;
};
